export const FlowchartConstants = {
  FLOWCHART_STEP_CLASS: 'flowchart-step',
  FLOWCHART_STEP_PLACEHOLDER_CLASS: 'flowchart-step-placeholder-class',

  FLOWCHART_CONNECTOR_CLASS: 'flowchart-connector',
  FLOWCHART_SCROLL_WIDTH_DIV_CLASS: 'flowchart-scroll-x-div',
  FLOWCHART_SCROLL_HEIGHT_DIV_CLASS: 'flowchart-scroll-y-div',
  FLOWCHART_STEPS_GAP: 50,
  FLOWCHART_STEP_PLACEHOLDER_CREATION_WIDTH_THRESHOLD: 20,
  FLOWCHART_STEP_PLACEHOLDER_CREATION_HEIGHT_THRESHOLD: 80,
  FLOWCHART_MIN_INLINE_PADDING: 100,
  FLOWCHART_MIN_BOTTOM_PADDING: 100,
  FLOWCHART_MIN_PLACEHOLDER_CREATION_DELAY: 500,
};

export const FlowchartConnectorsAnimationsConstants = {
  FLOWCHART_ANIMATE_CONNECTORS_CLASS: 'animate-connectors',
  STROKE_DASHARRAY: '6',
  STROKE_VALUES: '100; 0',
  DURATION: '4s',
};
